name-template: "$NEXT_MINOR_VERSION"
tag-template: "logstash-gelf-$NEXT_MINOR_VERSION"
template: |
    # What's New
    $CHANGES
categories:
  - title: 🚀 Features
    label: "type: enhancement"
  - title: 🐛 Bugfixes
    label: "type: bug"
  - title: 🐛 Regressions
    label: "type: regression"
  - title: 📖 Documentation
    label: "type/docs"
  - title: 📦 Dependency updates
    label: "type: dependency-upgrade"
