language: java

sudo: false

dist: trusty

group: edge

env:
  - MAVEN_SKIP_RC=true

cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.m2/wrapper'

matrix:
  include:
  - env: Java='9'
  - env: Java='10'
#  - env: Java='11'

before_install:
 - wget https://github.com/sormuras/bach/raw/support-older-jdks/install-jdk.sh 
 - source ./install-jdk.sh --verbose --feature ${Java}
 - src/test/bash/create_certificates.sh

install: make travis-install
script: make test

after_success:
  - test "${JDK_RELEASE}" = "Oracle JDK 9" && bash <(curl -s https://codecov.io/bash) || true

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/2f7029afba496c449d7d
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: false     # default: false
