language: java

sudo: false

dist: trusty

group: edge

env:
  - MAVEN_SKIP_RC=true

cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.m2/wrapper'

matrix:
  include:
    - jdk: oraclejdk8
# Java 9 (openjdk-9.0.1 fails with java.security.InvalidAlgorithmParameterException: the trustAnchors parameter must be non-empty)
    - jdk: oraclejdk9
      env: JDK_RELEASE='JDK 9'
# Java 10
    - env: JDK_RELEASE='JDK 10 Early-Access'
      install: . ./src/test/bash/install-jdk-10.sh
  allow_failures:
    - env: JDK_RELEASE='JDK 10 Early-Access'

before_install:
  - src/test/bash/create_certificates.sh

install: make travis-install
script: make test

after_success:
  - bash <(curl -s https://codecov.io/bash)

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/2f7029afba496c449d7d
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: false     # default: false
