language: java
install: make travis-install
script: make test-coveralls
sudo: false
cache:
  directories:
    - '$HOME/.m2/repository'
jdk:
  - oraclejdk8
  - oraclejdk7
  - openjdk6
notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/2f7029afba496c449d7d
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: false     # default: false
